### ISSUE TITLE
Crystal 0.23.1

### ISSUE THREAD

**Issue by mamantoha** [bbtfr/proxy.cr#1]
Hi!
I've tried this shard with the latest Crystal release, and it doesn't work.
Do you have any plans to maintain this library?

**Comment by mamantoha** [comment]
https://github.com/bbtfr/proxy.cr/pull/2

**Comment by bbtfr** [comment]
Sorry for the delay, I have been busy lately.
I saw your PR, would you like to re-open it?

**Comment by mamantoha** [comment]
Hi.
I've made a lot of changes includes change file structure and rename the project to `http_proxy_server`. You check it here https://github.com/mamantoha/http_proxy_server.
I can create new PR, but it will be incompatible with your repository.
What do you think? Should we merge our repositories?

**Comment by bbtfr** [comment]
ok, I think a new repo would be fine, since I don't have much time to maintain this project.
